### ISSUE TITLE
Is this role redundant if you're using configuration-as-code?

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-script-security#3]
I'm curious if this role provides anything over and above what the configuration as code plugin provides if you supply the following elements in your casc jenkins.yaml:

```
security:
  scriptApproval:
    approvedSignatures:
    - "method hudson.model.Run getDescription"
    - "method hudson.model.Run getId"
    .
    .
    .
```

Just curious, as I am using this role inherently by using your ansible-jenkins-pipeline-library role which includes it, but I also am installing the configuration-as-code plugin using that role, and placing my jenkins.yaml casc file (including script approval signatures) in the default location prior.

**Comment by tobias-richter** [comment]
When the roles were written JCasC was in the beginnings and scriptApproval was not supported.

The approach of the this role is a little bit different than the approach of JCasC. If you manage via JCasC, JCasC is the only one who controls the script security.

This Role is able to add and remove script approvals to existing Jenkins instances.
I think you should avoid to use both solutions as once.
